SeguimientoDocumentos/src/java/modelo/RevisionBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modelo;

import control.Revision;
import entity.Documentos;
import entity.Revisiones;
import entity.Usuarios;
import java.util.Collection;
import java.util.Date;
import java.util.List;
import javax.ejb.EJB;
import javax.enterprise.context.RequestScoped;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import sesion.DocumentoFacade;
import sesion.RevisionFacade;
import sesion.UsuarioFacade;

/**
 *
 * @author IthzaVG
 */
@ManagedBean
@RequestScoped
public class RevisionBean {

    private Date fecha;
    private int pagina;
    private int parrafo;
    private int status;
    private String comentario;
    private int idRevisor;
    private int idDoc;
    private int idRevision;

    @Inject
    private RevisionFacade revFacade;
    private Revisiones selected = new Revisiones();

    @EJB
    private RevisionFacade ejbFacade;
    private List<Documentos> documentos = null;
    private List<Usuarios> revisor = null;

    public RevisionFacade getRevFacade() {
        return revFacade;
    }

    public void setRevFacade(RevisionFacade revFacade) {
        this.revFacade = revFacade;
    }

    public Revisiones getSelected() {
        return selected;
    }

    public void setSelected(Revisiones selected) {
        this.selected = selected;
    }

    public RevisionFacade getEjbFacade() {
        return ejbFacade;
    }

    public void setEjbFacade(RevisionFacade ejbFacade) {
        this.ejbFacade = ejbFacade;
    }

    public List<Documentos> getDocumentos() {
        return documentos;
    }

    public void setDocumentos(List<Documentos> documentos) {
        this.documentos = documentos;
    }

    public List<Usuarios> getRevisor() {
        return revisor;
    }

    public void setRevisor(List<Usuarios> revisor) {
        this.revisor = revisor;
    }

    public Date getFecha() {
        return fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    public int getPagina() {
        return pagina;
    }

    public void setPagina(int pagina) {
        this.pagina = pagina;
    }

    public int getParrafo() {
        return parrafo;
    }

    public void setParrafo(int parrafo) {
        this.parrafo = parrafo;
    }

    public String getComentario() {
        return comentario;
    }

    public void setComentario(String comentario) {
        this.comentario = comentario;
    }

    public int getIdRevisor() {
        return idRevisor;
    }

    public void setIdRevisor(int idRevisor) {
        this.idRevisor = idRevisor;
    }

    public int getIdDoc() {
        return idDoc;
    }

    public void setIdDoc(int idDoc) {
        this.idDoc = idDoc;
    }

    public int getStatus() {
        return status;
    }

    public void setStatus(int status) {
        this.status = status;
    }

    public int getIdRevision() {
        return idRevision;
    }

    public void setIdRevision(int idRevision) {
        this.idRevision = idRevision;
    }

    public List<Revisiones> getRevisiones() {
        return this.revFacade.findAll();
    }
    
     private DocumentoFacade getFacade() {
        return ejbFacadeD;
    }
    @EJB
    private sesion.DocumentoFacade ejbFacadeD;
    public List<Documentos> getItemsAvailableSelectOneD() {
        return getFacade().findAll();
    }
   
    
    private UsuarioFacade getFacadeU() {
        return ejbFacadeU;
    }
    @EJB
    private sesion.UsuarioFacade ejbFacadeU;
    public List<Usuarios> getItemsAvailableSelectOneR() {
        return getFacadeU().findAll();
    }
    

    public String revDoc(int id) {

        Revisiones r = this.revFacade.find(id);
        this.pagina = r.getPagina();
        this.parrafo = r.getParrafo();
        this.comentario = r.getComentarios();
        this.idRevisor = r.getIdRevisor().getIdUsuario();
        this.idDoc = r.getIdDocumento().getIdDocumento();
        this.fecha = r.getFecha();

        return "dialogViews/observacionesDF";
    }

    public String eliminaObs(int id) {
        Revisiones rev = this.revFacade.find(id);
        this.revFacade.remove(rev);
        return "observacionesDF";

    }

    public String getIds(int id) {
        Revisiones ids = this.ejbFacade.find(id);
        this.idRevisor = ids.getIdRevisor().getIdUsuario();
        this.idDoc = ids.getIdDocumento().getIdDocumento();

        return "agregaObsDF";
    }

    public String agregaObs() {
        Revisiones r = new Revisiones();
        r.setIdDocumento(selected.getIdDocumento());
        r.setIdRevisor(selected.getIdRevisor());
        r.setPagina(selected.getPagina());
        r.setParrafo(selected.getParrafo());
        r.setComentarios(selected.getComentarios());
        r.setFecha(selected.getFecha());

        this.revFacade.create(r);
        this.idRevision = r.getIdRevision();
        return "agregaObsDF";

    }

}

SeguimientoDocumentos/web/dialogViews/actualizarDF.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <h:head>
        <title>Actualizar Documento</title>
        <h:outputStylesheet library="css" name="estilos.css"/>
    </h:head>

    <h:body>
        <ui:composition template="/template/master_1.xhtml">
            <ui:define name="contenido" class="BGC">
                <h:form enctype="multipart/form-data" >
                    <p:growl id="messages" showDetail="true" />

                    <h:panelGrid columns="1" >

                        <h:outputLabel class="text" value="Nombre "/> 
                        <p:inputText id="nom" label="nom" required="true"
                                     value="#{updateDoc.nombre}"/>


                        <p:inputText id="doc" label="doc" required="true" readonly="true"
                                     value="#{updateDoc.file}" style="display: none"/>


                        <p:inputText id="revi1" label="revi1" required="true"  readonly="true"
                                     value="#{updateDoc.idRev1}" style=" display: none"/>


                        <p:inputText id="revi2" label="revi2" required="true" readonly="true"
                                     value="#{updateDoc.idRev2}" style="display: none"/>

                        <h:outputLabel class="text" value="Fecha"/> 
                        <h:outputLabel value="#{updateDoc.fecha}">
                            <f:convertDateTime pattern="dd/MM/yyyy -  HH:mm:ss"/>
                        </h:outputLabel>

                        <br/>
                        <p:fileUpload  mode="simple"/>
                        <br/>        
                        <p:commandButton value="Subir" ajax="false" action="#{updateDoc.saveUpdate(updateDoc, updateDoc.idDoc)}"/>
                    </h:panelGrid>


                </h:form>
            </ui:define>

        </ui:composition>
    </h:body>
</html>

SeguimientoDocumentos/web/dialogViews/agregaObsDF.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title>Agrega observación</title>
        <h:outputStylesheet library="css" name="estilos.css"/>
    </h:head>
    <h:body>
        <ui:composition template="/template/master_1.xhtml">
            <ui:define name="contenido">
            <h:form>
            <p:growl id="msgs" showDetail="true" />
            <h:panelGrid columns="2">
                <h:outputLabel class="text" value="Documento "/>
                <p:selectOneMenu id="idDoc" value="#{revisionBean.selected.idDocumento}" required="true">
                    <f:selectItems value="#{revisionBean.itemsAvailableSelectOneD}"
                                   var="idDoc"
                                   itemValue="#{idDoc}"/>
                                   
                </p:selectOneMenu>
                <h:outputLabel class="text" value="Revisor "/>
                <p:selectOneMenu id="idrevi" value="#{revisionBean.selected.idRevisor}" required="true">
                    <f:selectItems value="#{revisionBean.itemsAvailableSelectOneR}"
                                   var="idRev"
                                   itemValue="#{idRev}"/>
                                  
                </p:selectOneMenu>
                <h:outputLabel class="text" value="Página: "/> 
                <p:inputText id="pag" label="pag" required="true" value="#{revisionBean.selected.pagina}">
                    <p:tooltip for="pag" value="Introduzca el número de página"/>
                </p:inputText>

                <h:outputLabel class="text" value="Párrafo:"/> 
                <p:inputText id="parrafo" label="parrafo" required="true" value="#{revisionBean.selected.parrafo}">
                    <p:tooltip for="parrafo" value="Introduzca el número de párrafo"/>
                </p:inputText>

                <h:outputLabel class="text" value="Comentario: "/> 
                <p:inputTextarea id="comentario" rows="10" cols="30"  
                                 queryDelay="750" minQueryLength="4" value="#{revisionBean.selected.comentarios}">
                  <p:tooltip for="comentario" value="Introduzca el comentario"/> 
                </p:inputTextarea>

                <div align="right"> 
                    <p:commandButton value="Enviar" 
                                     action="#{revisionBean.agregaObs()}"
                                     update="revisiones" ajax="false"></p:commandButton>
                </div>
                
                
            </h:panelGrid>
            <h:panelGrid columns="1">
                <p:dataTable id="revisiones" var="rev" value="#{revisionBean.revisiones}" paginator="true" >
                            <f:facet name="header">
                                Observaciones
                            </f:facet>
                            <p:column headerText="Fecha" id="fechaRev" >
                                <h:outputText value="#{rev.fecha}" >
                                    <f:convertDateTime pattern="dd/MM/yyyy -  HH:mm:ss"/>
                                </h:outputText>
                            </p:column>
                            <p:column headerText="Página" id="paginas">
                                <h:outputText value="#{rev.pagina}" />
                            </p:column>
                            <p:column headerText="Párrafo" id="parrafo">
                                <h:outputText value="#{rev.parrafo}" />
                            </p:column>
                            <p:column headerText="Comentario" id="comentario">
                                <h:outputText value="#{rev.comentarios}" />
                            </p:column>
                            <p:column headerText="Revisor" id="fecha">
                                <h:outputText value="#{rev.idRevisor.nombre}"/>
                            </p:column>

                            <p:column style="width:40px;text-align: center">
                                <h:commandButton   value="OK" title="Realizada" 
                                                   action="#{revisionBean.eliminaObs(rev.idRevision)}" />
                            </p:column>
                        </p:dataTable>
            </h:panelGrid>
        </h:form>
        </ui:define>
            
        </ui:composition>
        
    </h:body>
</html>


SeguimientoDocumentos/web/dialogViews/observacionesDF.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">
    <h:head>
        <title>Ver observaciones</title>
        <h:outputStylesheet library="css" name="estilos.css"/>
    </h:head>
    <h:body>
        <ui:composition template="/template/master_1.xhtml">

            <ui:define name="contenido">
                <h:form>
                    <h:panelGrid columns="1">
                        <p:dataTable id="revisiones" var="rev" value="#{revisionBean.revisiones}" paginator="true" >
                            <f:facet name="header">
                                Observaciones
                            </f:facet>
                            <p:column headerText="Fecha" id="fechaRev" >
                                <h:outputText value="#{rev.fecha}" >
                                    <f:convertDateTime pattern="dd/MM/yyyy -  HH:mm:ss"/>
                                </h:outputText>
                            </p:column>
                            <p:column headerText="Página" id="paginas">
                                <h:outputText value="#{rev.pagina}" />
                            </p:column>
                            <p:column headerText="Párrafo" id="parrafo">
                                <h:outputText value="#{rev.parrafo}" />
                            </p:column>
                            <p:column headerText="Comentario" id="comentario">
                                <h:outputText value="#{rev.comentarios}" />
                            </p:column>
                            <p:column headerText="Revisor" id="fecha">
                                <h:outputText value="#{rev.idRevisor.nombre}"/>
                            </p:column>

                            <p:column style="width:40px;text-align: center">
                                <h:commandButton   value="OK" title="Realizada" 
                                                   action="#{revisionBean.eliminaObs(rev.idRevision)}" />
                            </p:column>
                        </p:dataTable>
                    </h:panelGrid>
                </h:form>  
            </ui:define>
        </ui:composition>

    </h:body>
</html>
