SeguimientoDocumentos/src/java/modelo/DocRev1Bean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modelo;


import control.DocRev1Control;
import control.DocumentoControl;
import control.Documento;
import control.DocumentoRevisor;
import control.Revisores;
import control.RevisoresControl;
import entity.Usuarios;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Collection;
import static java.util.Collections.list;
import java.util.Date;
import java.util.List;
import javax.enterprise.context.RequestScoped;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.servlet.http.HttpServletResponse;
import org.apache.commons.io.IOUtils;
import org.primefaces.model.StreamedContent;
import org.primefaces.model.UploadedFile;

/**
 *
 * @author IthzaVG
 */
@ManagedBean
@RequestScoped
public class DocRev1Bean {
    
    private UploadedFile file;
    private int idDoc;
    private Collection<DocumentoRevisor> listaDocRev1= null;
    private String nombre;
    private  int status;
    private Usuarios idUsuario, idRev1,idRev2,idAutorizador;
    private final java.util.Date fecha = new Date();
    
    
    @Inject
    DocRev1Control revDoc;
    Documento documento;
    

    /**
     * Creates a new instance of fileBean
     */
    public DocRev1Bean() {
    }

    public UploadedFile getFile() {
        return file;
    }

    public void setFile(UploadedFile file) {
        this.file = file;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public int getStatus() {
        return status;
    }

    public void setStatus(int status) {
        this.status = status;
    }

    public Usuarios getIdUsuario() {
        return idUsuario;
    }

    public void setIdUsuario(Usuarios idUsuario) {
        this.idUsuario = idUsuario;
    }

    public Usuarios getIdRev1() {
        return idRev1;
    }

    public void setIdRev1(Usuarios idRev1) {
        this.idRev1 = idRev1;
    }

    public Usuarios getIdRev2() {
        return idRev2;
    }

    public void setIdRev2(Usuarios idRev2) {
        this.idRev2 = idRev2;
    }

    public Usuarios getIdAutorizador() {
        return idAutorizador;
    }

    public void setIdAutorizador(Usuarios idAutorizador) {
        this.idAutorizador = idAutorizador;
    }


    public int getIdDoc() {
        return idDoc;
    }

    public void setIdDoc(int idDoc) {
        this.idDoc = idDoc;
    }


    
     
     public Collection<DocumentoRevisor> getDocumentosRev1(){
         listaDocRev1 = revDoc.listaRD();
         return listaDocRev1;
     }
   
    
}

SeguimientoDocumentos/src/java/modelo/DocRev2Bean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modelo;


import control.DocRev1Control;
import control.DocRev2Control;
import control.DocumentoControl;
import control.Documento;
import control.DocumentoRevisor;
import control.Revisores;
import control.RevisoresControl;
import entity.Usuarios;
import java.io.IOException;
import java.io.InputStream;
import java.util.Collection;
import static java.util.Collections.list;
import java.util.Date;
import java.util.List;
import javax.enterprise.context.RequestScoped;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import org.apache.commons.io.IOUtils;
import org.primefaces.model.UploadedFile;

/**
 *
 * @author Richie1
 */
@ManagedBean
@RequestScoped
public class DocRev2Bean {
    
    private UploadedFile file;
    private Collection<DocumentoRevisor> listaDocRev2= null;
    private String nombre;
    private  int status;
    private Usuarios idUsuario, idRev1,idRev2,idAutorizador;
    private final java.util.Date fecha = new Date();
    private int idDoc;
    
    
    @Inject
    DocRev2Control revDoc;
    Documento documento;
    

    /**
     * Creates a new instance of fileBean
     */
    public DocRev2Bean() {
    }

    public UploadedFile getFile() {
        return file;
    }

    public void setFile(UploadedFile file) {
        this.file = file;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public int getStatus() {
        return status;
    }

    public void setStatus(int status) {
        this.status = status;
    }

    public Usuarios getIdUsuario() {
        return idUsuario;
    }

    public void setIdUsuario(Usuarios idUsuario) {
        this.idUsuario = idUsuario;
    }

    public Usuarios getIdRev1() {
        return idRev1;
    }

    public void setIdRev1(Usuarios idRev1) {
        this.idRev1 = idRev1;
    }

    public Usuarios getIdRev2() {
        return idRev2;
    }

    public void setIdRev2(Usuarios idRev2) {
        this.idRev2 = idRev2;
    }

    public Usuarios getIdAutorizador() {
        return idAutorizador;
    }

    public void setIdAutorizador(Usuarios idAutorizador) {
        this.idAutorizador = idAutorizador;
    }

    public int getIdDoc() {
        return idDoc;
    }

    public void setIdDoc(int idDoc) {
        this.idDoc = idDoc;
    }


    
     
     public Collection<DocumentoRevisor> getDocumentosRev2(){
         listaDocRev2 = revDoc.listaRD2();
         return listaDocRev2;
     }
     
    
}

SeguimientoDocumentos/src/java/modelo/DocumentoBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modelo;


import control.DocRev1Control;
import control.DocumentoControl;
import control.Documento;
import control.Revision;
import control.Revisores;
import control.RevisoresControl;
import entity.Revisiones;
import entity.Usuarios;
import java.io.IOException;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.Collection;
import static java.util.Collections.list;
import java.util.Date;
import java.util.List;
import javax.enterprise.context.RequestScoped;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import org.apache.commons.io.IOUtils;
import org.primefaces.model.UploadedFile;
import sesion.RevisionFacade;

/**
 *
 * @author IthzaVG
 */
@ManagedBean
@RequestScoped
public class DocumentoBean {
    
    private UploadedFile file;
    private Collection<Documento> listaDocumentos = null;
    private Collection<Documento> listaDocRev1= null;
    private String nombre;
    private  int status, idDoc;
    private Usuarios idUsuario, idRev1,idRev2,idAutorizador;
    private final java.util.Date fecha = new Date(); 
    
    
    @Inject
    DocumentoControl creaDocumento;
    DocRev1Control revDoc;
    Documento documento;
    

    /**
     * Creates a new instance of fileBean
     */
    public DocumentoBean() {
    }

    public UploadedFile getFile() {
        return file;
    }

    public void setFile(UploadedFile file) {
        this.file = file;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public int getStatus() {
        return status;
    }

    public void setStatus(int status) {
        this.status = status;
    }

    public Usuarios getIdUsuario() {
        return idUsuario;
    }

    public void setIdUsuario(Usuarios idUsuario) {
        this.idUsuario = idUsuario;
    }

    public Usuarios getIdRev1() {
        return idRev1;
    }

    public void setIdRev1(Usuarios idRev1) {
        this.idRev1 = idRev1;
    }

    public Usuarios getIdRev2() {
        return idRev2;
    }

    public void setIdRev2(Usuarios idRev2) {
        this.idRev2 = idRev2;
    }

    public Usuarios getIdAutorizador() {
        return idAutorizador;
    }

    public void setIdAutorizador(Usuarios idAutorizador) {
        this.idAutorizador = idAutorizador;
    }

    public int getIdDoc() {
        return idDoc;
    }

    public void setIdDoc(int idDoc) {
        this.idDoc = idDoc;
    }

    

    
    public void upload() throws IOException{
      InputStream input = file.getInputstream();
      byte[] doc = IOUtils.toByteArray(input);
        
        documento = new Documento(idDoc,doc,nombre,status,idUsuario,idRev1,idRev2,idAutorizador,fecha);
        
        if (creaDocumento.agregaDocumento(documento)) {
            
            FacesMessage msg = new FacesMessage("Se guardó correctamente");
            FacesContext.getCurrentInstance().addMessage(null, msg);
            
        }else{
            FacesMessage msg = new FacesMessage("Ocurrió un error al guardar su archivo intente nuevamente");
            FacesContext.getCurrentInstance().addMessage(null, msg);
        }
        
    }

    
    
     public Collection<Documento> getDocumentos(){
        
        listaDocumentos= creaDocumento.listaDocus();
        return listaDocumentos;
        
    }

  

    
}

SeguimientoDocumentos/src/java/modelo/LoginBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modelo;

import java.io.IOException;
import java.io.Serializable;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.application.FacesMessage;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;

/**
 *
 * @author lili
 */
@Named(value = "loginBean")
@SessionScoped
public class LoginBean implements Serializable {

    private String correo;
    private String password;

    /**
     * Creates a new instance of LoginBean
     */
    public LoginBean() {
    }

    public String login() throws IOException {
        FacesContext context = FacesContext.getCurrentInstance();
        ExternalContext externalContext = context.getExternalContext();
        HttpServletRequest request = (HttpServletRequest) externalContext.getRequest();
        String pagina = null;
        try {
            System.out.println("datos"+correo+password);
            request.login(correo, password);
            if (request.isUserInRole("1")) {
                pagina = "/1/creador";
            } else {
                if (request.isUserInRole("2")) {
                    pagina = "/2/revisor1";
                } else 
                
                if (request.isUserInRole("3")) {
                    pagina = "/3/revisor2";
                } else
                 
                 if (request.isUserInRole("4")) {
                    pagina = "/4/autorizador";
                } else
                 
                {
                 
                    context.addMessage(null, new FacesMessage("Credenciales insuficientes"));
                    pagina = "/faces/login_error.xhtml";
                }
            }
        } catch (ServletException e) {
            context.addMessage(null, new FacesMessage("Error en la convinación usuario/contraseña"));
            System.out.println("error-----------------------------------------------------");
        }
        return pagina;
    }

    public void logout() throws IOException {
        ExternalContext externalContext = FacesContext.getCurrentInstance().getExternalContext();
        externalContext.invalidateSession();
        externalContext.redirect(externalContext.getRequestContextPath() + "/faces/login.xhtml");
    }

    public String getCorreo() {
        return correo;
    }

    public void setCorreo(String correo) {
        this.correo = correo;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

 

}

SeguimientoDocumentos/src/java/modelo/RevisoresDosBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modelo;

import control.Documento;
import control.Revisores;
import control.RevisoresControl;
import control.RevisoresControlDos;
import java.util.Collection;
import javax.inject.Named;
import javax.enterprise.context.RequestScoped;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.context.FacesContext;
import javax.inject.Inject;

/**
 *
 * @author IthzaVG
 */
@ManagedBean
@RequestScoped
public class RevisoresDosBean {
private int id;
private String nombre;
private String apellidos;
private String correo;
private String password;
private int tipo;

private Collection<Revisores> listaRevisoresDos = null;

@Inject
 RevisoresControlDos muestraRevisorDos;

    public RevisoresDosBean() {
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }
 
    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getApellidos() {
        return apellidos;
    }

    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }

    public String getCorreo() {
        return correo;
    }

    public void setCorreo(String correo) {
        this.correo = correo;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public int getTipo() {
        return tipo;
    }

    public void setTipo(int tipo) {
        this.tipo = tipo;
    }
    
   
    
    public Collection<Revisores> getRevisores(){
         
             listaRevisoresDos = muestraRevisorDos.listaRevisores();
      
        return listaRevisoresDos;
    }
}

SeguimientoDocumentos/web/creador.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">
    <h:head>
        <title>Facelet Title</title>
        <h:outputStylesheet library="css" name="estilos.css"/>
    </h:head>
    <h:body>
        <ui:composition template="/template/master_1.xhtml">
            <ui:define name="titulo">SD || Seguimiento Documentos - Creador</ui:define>

            <!-- 
            <ui:define name="header">
                <ui:include src="template/header.xhtml"/>
            </ui:define>
            -->

            <ui:define name="west">
                <ui:include src="template/ladoIzdo.xhtml"/>
            </ui:define> 

            <ui:define name="contenido" class="BGC">
                <h:form>
                    <div align="right">
                        <p:commandButton value="Salir"></p:commandButton>
                    </div>
                </h:form>
                <div align="left" style="background-color: #d6d4d4; align-content: left; height:30px ;width: 100%">
                    <h:outputLabel class="h1" value="Bienvenido al Módulo de Seguimiento del documento"/>    
                </div>
                <div align="" style="background-color: #f6f6f6; height:100%; width: 100%">
                    <br/>
                    <h:outputLabel class="text" value="Para subir un documento por 
                                   favor llena los campos correspondientes y continua dando clic en subir"/>
                    <br/> <br/>                    

                    <h:form enctype="multipart/form-data">
                        <p:growl id="msgs" showDetail="true" />
                        <h:panelGrid columns="2">
                            <h:outputLabel class="text" value="Nombre del documento: "/> 
                            <p:inputText id="nombredoc" label="nombredoc" required="true" value="#{documentoBean.nombre}">
                                <p:tooltip for="nombredoc" value="Introduzca el nombre del documento"/>
                                <f:validateLength minimum="2" />
                            </p:inputText>
                            <p:outputLabel class="text" value="Primer revisor:  " />
                            <p:selectOneMenu required="true" id="rev"  style="width:220px">
                                <f:selectItem itemLabel="Selecciona un revisor" itemValue=""  />
                                <f:selectItems  value="#{revisoresUnoBean.revisores}" var ="r" itemLabel="#{r.nombre}" itemValue="#{r.id}" />
                            </p:selectOneMenu>

                            <p:outputLabel class="text" value="Segundo revisor:  " />
                            <p:selectOneMenu id="rev2" required="true" style="width:220px">
                                <f:selectItem itemLabel="Selecciona un revisor" itemValue=""  />
                                <f:selectItems  value="#{revisoresDosBean.revisores}" var ="r" itemLabel="#{r.nombre}" itemValue="#{r.id}" />
                            </p:selectOneMenu>
                        </h:panelGrid>
                        <h:panelGrid columns="1">
                            <p:fileUpload required="true"  value="#{documentoBean.file}" mode="simple"/>
                            <p:commandButton value="Subir" action="#{documentoBean.upload()}" ajax="false"/>
                        </h:panelGrid>
                        <br/><br/>

                    </h:form>

                    <h:form>
                        <h:panelGrid columns="1">
                            <p:dataTable id="docTable" var="doc" value="#{updateDoc.documentos}" paginator="true" >
                                <f:facet name="header">
                                    Historial de Documentos
                                </f:facet>
                                <p:column headerText="IdDoc" id="idDoc" style="width: 50px">
                                    <h:outputText value="#{doc.idDocumento}" />
                                </p:column>
                                <p:column headerText="Nombre" id="nombre">
                                    <h:outputText value="#{doc.nombre}" />
                                </p:column>
                                <p:column headerText="Revisor 1" id="revisor1">
                                    <h:outputText value="#{doc.idRev1}" />
                                </p:column>
                                <p:column headerText="Revisor 2" id="revisor2">
                                    <h:outputText value="#{doc.idRev2}" />
                                </p:column>
                                <p:column headerText="Fecha de creación" id="fecha">
                                    <h:outputText value="#{doc.fechaCreacion}">
                                        <f:convertDateTime pattern="dd/MM/yyyy -  HH:mm:ss"/>
                                    </h:outputText>
                                </p:column>
                                <p:column headerText="Estatus" id="status">
                                    <h:outputText value="Primera revisón" rendered="#{doc.status eq 0}" />
                                    <h:outputText value="Segunda revisón" rendered="#{doc.status eq 1}" />
                                    <h:outputText value="Autorizado" rendered="#{doc.status eq 2}" />
                                </p:column>
                                <p:column style="width:40px;text-align: center">
                                    <p:commandButton  icon="ui-icon-search" title="Observaciones" 
                                                      onclick="target = '_blank'" 
                                                      action="#{revisionBean.revDoc(doc.idDocumento)}" 
                                                      ajax="false"/>


                                </p:column>
                                <p:column style="width: 40px; text-align: center">
                                    <p:commandButton icon="ui-icon-pencil" 
                                                     title="Actualizar" onclick="target = '_blank'" 
                                                     action="#{updateDoc.update(doc.idDocumento)}" 
                                                     ajax="false" />
                                </p:column>
                                <p:column style="width:60px; text-align: center">
                                    <h:commandButton   value="Borrar" title="Eliminar documento" 
                                                       action="#{updateDoc.eliminaDoc(doc.idDocumento)}" />
                                </p:column>
                            </p:dataTable>
                            <p:commandButton  value="Actualizar" update="docTable" ajax="false"/>
                        </h:panelGrid>
                    </h:form>
                    <br/>
                </div>
            </ui:define>

            <ui:define name="pie">
                <ui:include src="template/footer.xhtml"/>
            </ui:define>
        </ui:composition>
    </h:body>
</html>


SeguimientoDocumentos/web/revisorDos.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">
    <h:head>
        <title>Facelet Title</title>
        <h:outputStylesheet library="css" name="estilos.css"/>
    </h:head>
    <h:body>
        <ui:composition template="/template/master_1.xhtml">
            <ui:define name="titulo">SD || Seguimiento Documentos - Revisor Dos </ui:define>

            <!-- 
            <ui:define name="header">
                <ui:include src="template/header.xhtml"/>
            </ui:define>
            -->

            <ui:define name="west">
                <ui:include src="template/ladoIzdo.xhtml"/>
            </ui:define> 

            <ui:define name="contenido" class="BGC">
                 <h:form>
                    <div align="right">
                        <p:commandButton value="Salir"></p:commandButton>
                    </div>
                </h:form>
                <div align="left" style="background-color: #d6d4d4; align-content:left ;height:30px ;width: 100%">
                    <h:outputLabel class="h1" value="Bienvenido al Módulo de Seguimiento del documento"/>    
                </div>
                <div align="" style="background-color: #f6f6f6; height:100%; width: 100%">
                    <br/>
                    <h:outputLabel class="text" value="A continuación se muestran los documentos a revisar"/>
                    <br/>
                    <br/>                    
                    <h:form id="documentos">
                        <p:growl id="msgs" showDetail="true" />

                        <p:dataTable id="basicDT" var="doc" value="#{docRev2Bean.documentosRev2}" paginator="true" >
                            <f:facet name="header">
                                Documentos a revisar
                            </f:facet>
                            <p:column headerText="id_documento">
                                <h:outputText value="#{doc.idDocumento}" />
                            </p:column>
                            <p:column headerText="Nombre">
                                <h:outputText value="#{doc.nombre}" />
                            </p:column>
                            <p:column headerText="Creador">
                                <h:outputText value="#{doc.idUsuario}" />
                            </p:column>
                            <p:column headerText="Fecha_creación">
                                <h:outputText value="#{doc.fecha}">
                                    <f:convertDateTime pattern="dd/MM/yyyy -  HH:mm:ss"/> 
                                </h:outputText>
                            </p:column>
                            <p:column headerText="Estatus">
                                <h:outputText value="Segunda revisón" rendered="#{doc.status eq 1}" />
                            </p:column>
                            <p:column style="width:40px;text-align: center">
                                <p:commandButton  actionListener="#{verDocRev1Bean.ver(event)}" icon="ui-icon-search" title="Ver documento" ajax="false" onclick="target='_blank'" >
                                    <f:param name="id_documento" value="#{doc.idDocumento}"></f:param>
                                    <f:ajax render="@form"/>
                                </p:commandButton>
                            </p:column>
                            <p:column style="width: 40px; text-align: center">
                                <p:commandButton action="#{agregaObsDF.agregaObsDoc()}" icon="ui-icon-pencil" title="Agregar Observacion"></p:commandButton>
                            </p:column>
                            <p:column style="width: 40px; text-align: center">
                                <p:commandButton icon="ui-icon-check" title="Aprobar"></p:commandButton>
                            </p:column>
                        </p:dataTable>


                    </h:form>
                    <br/>
                </div>


            </ui:define>

            <ui:define name="pie">
                <ui:include src="template/footer.xhtml"/>
            </ui:define>
        </ui:composition>
    </h:body>
</html>


SeguimientoDocumentos/web/revisorUno.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">
    <h:head>
        <title>Facelet Title</title>
        <h:outputStylesheet library="css" name="estilos.css"/>
    </h:head>
    <h:body>
        <ui:composition template="/template/master_1.xhtml">
            <ui:define name="titulo">SD || Seguimiento Documentos - Revisor</ui:define>

            <!-- 
            <ui:define name="header">
                <ui:include src="template/header.xhtml"/>
            </ui:define>
            -->

            <ui:define name="west">
                <ui:include src="template/ladoIzdo.xhtml"/>
            </ui:define> 

            <ui:define name="contenido" class="BGC">
                <h:form>
                    <div align="right">
                        <p:commandButton value="Salir"></p:commandButton>
                    </div>
                </h:form>
                <div align="left" style="background-color: #d6d4d4; align-content:left; height:30px ;width: 100%">
                    <h:outputLabel class="h1" value="Bienvenido al Módulo de Seguimiento del documento"/>    
                </div>
                <div align="" style="background-color: #f6f6f6; height:100%; width: 100%">
                    <br/>
                    <h:outputLabel class="text" value="A continuación se muestran los documentos a revisar"/>
                    <br/>
                    <br/>                    
                    <h:form id="documentos">
                        <p:growl id="msgs" showDetail="true" />

                        <p:dataTable id="basicDT" var="doc" value="#{docRev1Bean.documentosRev1}" paginator="true"  >
                            <f:facet name="header">
                                Documentos a revisar
                            </f:facet>
                            <p:column headerText="id_Documento">
                                <h:outputText value="#{doc.idDocumento}" />
                            </p:column>
                            <p:column headerText="Nombre">
                                <h:outputText value="#{doc.nombre}" />
                            </p:column>
                            <p:column headerText="Creador">
                                <h:outputText value="#{doc.idUsuario}" />
                            </p:column>
                            <p:column headerText="Fecha_creación">
                                <h:outputText value="#{doc.fecha}" />
                            </p:column>
                            <p:column headerText="Estatus">
                                <h:outputText value="Primera revisón" rendered="#{doc.status eq 0}" />
                            </p:column>
                            <p:column style="width:40px;text-align: center">
                                <p:commandButton  actionListener="#{verDocRev1Bean.ver(event)}" icon="ui-icon-search" title="Ver documento" ajax="false" onclick="target = '_blank'" >
                                    <f:param name="id_documento" value="#{doc.idDocumento}"></f:param>
                                    <f:ajax render="@form"/>
                                </p:commandButton>
                            </p:column>
                            <p:column style="width: 40px; text-align: center">
                                <p:commandButton icon="ui-icon-check" title="Aprobar"></p:commandButton>
                            </p:column>


                        </p:dataTable><br/>
                        <div align="right">
                            <p:commandButton action="/dialogViews/agregaObsDF.xhtml" 
                                             icon="ui-icon-pencil" value="Agregar observacion" title="Agregar Observacion" 
                                             onclick="target = '_blank'" ajax="false"></p:commandButton>
                        </div>

                    </h:form>
                    <br/>
                </div>


            </ui:define>

            <ui:define name="pie">
                <ui:include src="template/footer.xhtml"/>
            </ui:define>
        </ui:composition>
    </h:body>
</html>
