Registro/crudUpdate/src/java/controlador/DocumentosController.java
package controlador;

import entidad.Documentos;
import controlador.util.JsfUtil;
import controlador.util.JsfUtil.PersistAction;
import sesion.DocumentosFacade;

import java.io.Serializable;
import java.util.List;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.ejb.EJB;
import javax.ejb.EJBException;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;

@Named("documentosController")
@SessionScoped
public class DocumentosController implements Serializable {

    @EJB
    private sesion.DocumentosFacade ejbFacade;
    private List<Documentos> items = null;
    private Documentos selected;

    public DocumentosController() {
    }

    public Documentos getSelected() {
        return selected;
    }

    public void setSelected(Documentos selected) {
        this.selected = selected;
    }

    protected void setEmbeddableKeys() {
    }

    protected void initializeEmbeddableKey() {
    }

    private DocumentosFacade getFacade() {
        return ejbFacade;
    }

    public Documentos prepareCreate() {
        selected = new Documentos();
        initializeEmbeddableKey();
        return selected;
    }

    public void create() {
        persist(PersistAction.CREATE, ResourceBundle.getBundle("/Bundle").getString("DocumentosCreated"));
        if (!JsfUtil.isValidationFailed()) {
            items = null;    // Invalidate list of items to trigger re-query.
        }
    }

    public void update() {
        if (selected.getStatus()==1){
            
        }
        persist(PersistAction.UPDATE, ResourceBundle.getBundle("/Bundle").getString("DocumentosUpdated"));
    }

    public void destroy() {
        persist(PersistAction.DELETE, ResourceBundle.getBundle("/Bundle").getString("DocumentosDeleted"));
        if (!JsfUtil.isValidationFailed()) {
            selected = null; // Remove selection
            items = null;    // Invalidate list of items to trigger re-query.
        }
    }

    public List<Documentos> getItems() {
            items = ejbFacade.docsRev1();  
        return items;
    }
    
    

    private void persist(PersistAction persistAction, String successMessage) {
        if (selected != null) {
            setEmbeddableKeys();
            try {
                if (persistAction != PersistAction.DELETE) {
                    getFacade().edit(selected);
                } else {
                    getFacade().remove(selected);
                }
                JsfUtil.addSuccessMessage(successMessage);
            } catch (EJBException ex) {
                String msg = "";
                Throwable cause = ex.getCause();
                if (cause != null) {
                    msg = cause.getLocalizedMessage();
                }
                if (msg.length() > 0) {
                    JsfUtil.addErrorMessage(msg);
                } else {
                    JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
                }
            } catch (Exception ex) {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, null, ex);
                JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            }
        }
    }

    public Documentos getDocumentos(java.lang.Integer id) {
        return getFacade().find(id);
    }

    public List<Documentos> getItemsAvailableSelectMany() {
        return getFacade().findAll();
    }

    public List<Documentos> getItemsAvailableSelectOne() {
        return getFacade().findAll();
    }

    @FacesConverter(forClass = Documentos.class)
    public static class DocumentosControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            DocumentosController controller = (DocumentosController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "documentosController");
            return controller.getDocumentos(getKey(value));
        }

        java.lang.Integer getKey(String value) {
            java.lang.Integer key;
            key = Integer.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Integer value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Documentos) {
                Documentos o = (Documentos) object;
                return getStringKey(o.getIdDocumento());
            } else {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, "object {0} is of type {1}; expected type: {2}", new Object[]{object, object.getClass().getName(), Documentos.class.getName()});
                return null;
            }
        }

    }

}

Registro/crudUpdate/web/documentos/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="DocumentosCreateDlg" widgetVar="DocumentosCreateDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.CreateDocumentosTitle}">
            <h:form id="DocumentosCreateForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{documentosController.selected != null}">
                        <p:outputLabel value="#{bundle.CreateDocumentosLabel_idDocumento}" for="idDocumento" />
                        <p:inputText id="idDocumento" value="#{documentosController.selected.idDocumento}" title="#{bundle.CreateDocumentosTitle_idDocumento}" required="true" requiredMessage="#{bundle.CreateDocumentosRequiredMessage_idDocumento}"/>
                        <p:outputLabel value="#{bundle.CreateDocumentosLabel_nombre}" for="nombre" />
                        <p:inputText id="nombre" value="#{documentosController.selected.nombre}" title="#{bundle.CreateDocumentosTitle_nombre}" required="true" requiredMessage="#{bundle.CreateDocumentosRequiredMessage_nombre}"/>
                        <p:outputLabel value="#{bundle.CreateDocumentosLabel_documento}" for="documento" />
                        <p:inputTextarea rows="4" cols="30" id="documento" value="#{documentosController.selected.documento}" title="#{bundle.CreateDocumentosTitle_documento}" required="true" requiredMessage="#{bundle.CreateDocumentosRequiredMessage_documento}"/>
                        <p:outputLabel value="#{bundle.CreateDocumentosLabel_fechaCreacion}" for="fechaCreacion" />
                        <p:calendar id="fechaCreacion" pattern="MM/dd/yyyy HH:mm:ss" value="#{documentosController.selected.fechaCreacion}" title="#{bundle.EditDocumentosTitle_fechaCreacion}" required="true" requiredMessage="#{bundle.EditDocumentosRequiredMessage_fechaCreacion}" showOn="button"/>
                        <p:outputLabel value="#{bundle.CreateDocumentosLabel_status}" for="status" />
                        <p:inputText id="status" value="#{documentosController.selected.status}" title="#{bundle.CreateDocumentosTitle_status}" required="true" requiredMessage="#{bundle.CreateDocumentosRequiredMessage_status}"/>
                        <p:outputLabel value="#{bundle.CreateDocumentosLabel_fechaAutorizacion}" for="fechaAutorizacion" />
                        <p:calendar id="fechaAutorizacion" pattern="MM/dd/yyyy HH:mm:ss" value="#{documentosController.selected.fechaAutorizacion}" title="#{bundle.EditDocumentosTitle_fechaAutorizacion}"  showOn="button"/>
                        <p:outputLabel value="#{bundle.CreateDocumentosLabel_idUsuario}" for="idUsuario" />
                        <p:selectOneMenu id="idUsuario" value="#{documentosController.selected.idUsuario}" required="true" requiredMessage="#{bundle.EditDocumentosRequiredMessage_idUsuario}">
                            <f:selectItems value="#{usuariosController.itemsAvailableSelectOne}"
                                           var="idUsuarioItem"
                                           itemValue="#{idUsuarioItem}"/>
                        </p:selectOneMenu>
                        <p:outputLabel value="#{bundle.CreateDocumentosLabel_idRev2}" for="idRev2" />
                        <p:selectOneMenu id="idRev2" value="#{documentosController.selected.idRev2}" required="true" requiredMessage="#{bundle.EditDocumentosRequiredMessage_idRev2}">
                            <f:selectItems value="#{usuariosController.itemsAvailableSelectOne}"
                                           var="idRev2Item"
                                           itemValue="#{idRev2Item}"/>
                        </p:selectOneMenu>
                        <p:outputLabel value="#{bundle.CreateDocumentosLabel_idRev1}" for="idRev1" />
                        <p:selectOneMenu id="idRev1" value="#{documentosController.selected.idRev1}" required="true" requiredMessage="#{bundle.EditDocumentosRequiredMessage_idRev1}">
                            <f:selectItems value="#{usuariosController.itemsAvailableSelectOne}"
                                           var="idRev1Item"
                                           itemValue="#{idRev1Item}"/>
                        </p:selectOneMenu>
                        <p:outputLabel value="#{bundle.CreateDocumentosLabel_idAutorizador}" for="idAutorizador" />
                        <p:selectOneMenu id="idAutorizador" value="#{documentosController.selected.idAutorizador}" required="true" requiredMessage="#{bundle.EditDocumentosRequiredMessage_idAutorizador}">
                            <f:selectItems value="#{usuariosController.itemsAvailableSelectOne}"
                                           var="idAutorizadorItem"
                                           itemValue="#{idAutorizadorItem}"/>
                        </p:selectOneMenu>
                    </p:panelGrid>
                    <p:commandButton actionListener="#{documentosController.create}" value="#{bundle.Save}" update="display,:DocumentosListForm:datalist,:growl" oncomplete="handleSubmit(args,'DocumentosCreateDialog');"/>
                    <p:commandButton value="#{bundle.Cancel}" onclick="DocumentosCreateDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>

Registro/crudUpdate/web/documentos/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>
        <p:dialog id="DocumentosEditDlg" widgetVar="DocumentosEditDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.EditDocumentosTitle}">
            <h:form id="DocumentosEditForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{documentosController.selected != null}">
                        <p:outputLabel value="#{bundle.EditDocumentosLabel_idDocumento}" for="idDocumento" />
                        <p:inputText id="idDocumento" disabled="true" value="#{documentosController.selected.idDocumento}" title="#{bundle.EditDocumentosTitle_idDocumento}" required="true" requiredMessage="#{bundle.EditDocumentosRequiredMessage_idDocumento}"/>
                        <p:outputLabel value="#{bundle.EditDocumentosLabel_nombre}" for="nombre" />
                        <p:inputText id="nombre" value="#{documentosController.selected.nombre}" disabled="true" title="#{bundle.EditDocumentosTitle_nombre}" required="true" requiredMessage="#{bundle.EditDocumentosRequiredMessage_nombre}"/>
                        <p:outputLabel value="#{bundle.EditDocumentosLabel_fechaCreacion}" for="fechaCreacion" />
                        <p:calendar id="fechaCreacion" disabled="true" pattern="MM/dd/yyyy HH:mm:ss" value="#{documentosController.selected.fechaCreacion}" title="#{bundle.EditDocumentosTitle_fechaCreacion}" required="true" requiredMessage="#{bundle.EditDocumentosRequiredMessage_fechaCreacion}" showOn="button"/>
<!--                    <p:outputLabel value="#{bundle.EditDocumentosLabel_documento}" for="documento" />
                        <p:inputTextarea rows="4" cols="30" disabled="true" id="documento" value="#{documentosController.selected.documento}" title="#{bundle.EditDocumentosTitle_documento}" required="true" requiredMessage="#{bundle.EditDocumentosRequiredMessage_documento}"/>-->                        
<!--                    <p:outputLabel value="#{bundle.EditDocumentosLabel_status}" for="status" />
                        <p:inputText id="status" disabled="true" value="#{documentosController.selected.status}" title="#{bundle.EditDocumentosTitle_status}" required="true" requiredMessage="#{bundle.EditDocumentosRequiredMessage_status}"/>-->
<!--                    <p:outputLabel value="#{bundle.EditDocumentosLabel_fechaAutorizacion}" for="fechaAutorizacion" />
                        <p:calendar id="fechaAutorizacion" disabled="true" pattern="MM/dd/yyyy HH:mm:ss" value="#{documentosController.selected.fechaAutorizacion}" title="#{bundle.EditDocumentosTitle_fechaAutorizacion}"  showOn="button"/>-->
<!--                        <p:outputLabel value="#{bundle.EditDocumentosLabel_idUsuario}" for="idUsuario" />
                        <p:selectOneMenu id="idUsuario" value="#{documentosController.selected.idUsuario}" required="true" requiredMessage="#{bundle.EditDocumentosRequiredMessage_idUsuario}">
                            <f:selectItem itemLabel="#{bundle.SelectOneMessage}"/>
                            <f:selectItems value="#{usuariosController.itemsAvailableSelectOne}"
                                           var="idUsuarioItem"
                                           itemValue="#{idUsuarioItem}"/>
                        </p:selectOneMenu>
                        <p:outputLabel value="#{bundle.EditDocumentosLabel_idRev2}" for="idRev2" />
                        <p:selectOneMenu id="idRev2" value="#{documentosController.selected.idRev2}" required="true" requiredMessage="#{bundle.EditDocumentosRequiredMessage_idRev2}">
                            <f:selectItem itemLabel="#{bundle.SelectOneMessage}"/>
                            <f:selectItems value="#{usuariosController.itemsAvailableSelectOne}"
                                           var="idRev2Item"
                                           itemValue="#{idRev2Item}"/>
                        </p:selectOneMenu>
                        <p:outputLabel value="#{bundle.EditDocumentosLabel_idRev1}" for="idRev1" />
                        <p:selectOneMenu id="idRev1" value="#{documentosController.selected.idRev1}" required="true" requiredMessage="#{bundle.EditDocumentosRequiredMessage_idRev1}">
                            <f:selectItem itemLabel="#{bundle.SelectOneMessage}"/>
                            <f:selectItems value="#{usuariosController.itemsAvailableSelectOne}"
                                           var="idRev1Item"
                                           itemValue="#{idRev1Item}"/>
                        </p:selectOneMenu>
                        <p:outputLabel value="#{bundle.EditDocumentosLabel_idAutorizador}" for="idAutorizador" />
                        <p:selectOneMenu id="idAutorizador" value="#{documentosController.selected.idAutorizador}" required="true" requiredMessage="#{bundle.EditDocumentosRequiredMessage_idAutorizador}">
                            <f:selectItem itemLabel="#{bundle.SelectOneMessage}"/>
                            <f:selectItems value="#{usuariosController.itemsAvailableSelectOne}"
                                           var="idAutorizadorItem"
                                           itemValue="#{idAutorizadorItem}"/>
                        </p:selectOneMenu>-->
                        
                        <p:selectOneButton required="false" value="#{documentosController.selected.status}" id="status">
                            <f:selectItem itemLabel="No aceptado" itemValue="0"/>
                            <f:selectItem itemLabel="Aceptado" itemValue="1"/>
                        </p:selectOneButton>
                    </p:panelGrid>
                    <p:commandButton actionListener="#{documentosController.update}" value="#{bundle.Save}" update="display,:DocumentosListForm:datalist,:growl, :DocumentosListForm" oncomplete="handleSubmit(args, 'DocumentosEditDialog');"/>
                    <p:commandButton value="#{bundle.Cancel}" onclick="DocumentosEditDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>
    </ui:composition>   
</html>

Registro/crudUpdate/web/documentos/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition template="/template.xhtml">


        <ui:define name="title">
            <h:outputText value="#{bundle.ListDocumentosTitle}"></h:outputText>
        </ui:define>
<!--        <f:event type="preRenderViewEvent" listener="#{documentosController.items}"/>-->
        <ui:define name="body">
            <h:form id="DocumentosListForm">
                <p:panel header="Documentos a revisar">
                    <p:dataTable id="datalist" value="#{documentosController.items}" var="item"
                                 selectionMode="single" selection="#{documentosController.selected}"
                                 paginator="true"
                                 rowKey="#{item.idDocumento}"
                                 rows="10"
                                 rowsPerPageTemplate="10,20,30,40,50"
                                 
                                 >

                        <p:ajax event="rowSelect"   update="createButton viewButton editButton deleteButton"/>
                        <p:ajax event="rowUnselect" update="createButton viewButton editButton deleteButton"/>

                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListDocumentosTitle_idDocumento}"/>
                            </f:facet>
                            <h:outputText value="#{item.idDocumento}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListDocumentosTitle_nombre}"/>
                            </f:facet>
                            <h:outputText value="#{item.nombre}"/>
                        </p:column>
<!--                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListDocumentosTitle_documento}"/>
                            </f:facet>
                            <h:outputText value="#{item.documento}"/>
                        </p:column>-->
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListDocumentosTitle_fechaCreacion}"/>
                            </f:facet>
                            <h:outputText value="#{item.fechaCreacion}">
                                <f:convertDateTime pattern="MM/dd/yyyy HH:mm:ss" />
                            </h:outputText>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListDocumentosTitle_status}"/>
                            </f:facet>
                            <h:outputText value="#{item.status}"/>
                        </p:column>
<!--                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListDocumentosTitle_fechaAutorizacion}"/>
                            </f:facet>
                            <h:outputText value="#{item.fechaAutorizacion}">
                                <f:convertDateTime pattern="MM/dd/yyyy HH:mm:ss" />
                            </h:outputText>
                        </p:column>-->
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListDocumentosTitle_idUsuario}"/>
                            </f:facet>
                            <h:outputText value="#{item.idUsuario}"/>
                        </p:column>
<!--                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListDocumentosTitle_idRev2}"/>
                            </f:facet>
                            <h:outputText value="#{item.idRev2}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListDocumentosTitle_idRev1}"/>
                            </f:facet>
                            <h:outputText value="#{item.idRev1}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListDocumentosTitle_idAutorizador}"/>
                            </f:facet>
                            <h:outputText value="#{item.idAutorizador}"/>
                        </p:column>-->
                        <f:facet name="footer">
                            <p:commandButton rendered="false" id="createButton" icon="ui-icon-plus"   value="#{bundle.Create}" actionListener="#{documentosController.prepareCreate}" update=":DocumentosCreateForm" oncomplete="PF('DocumentosCreateDialog').show()"/>
                            <p:commandButton id="viewButton"   icon="ui-icon-search" value="#{bundle.View}" update=":DocumentosViewForm" oncomplete="PF('DocumentosViewDialog').show()" disabled="#{empty documentosController.selected}"/>
                            <p:commandButton id="editButton"   icon="ui-icon-pencil" value="#{bundle.Edit}" update=":DocumentosEditForm" oncomplete="PF('DocumentosEditDialog').show()" disabled="#{empty documentosController.selected}"/>
                            <p:commandButton rendered="false" id="deleteButton" icon="ui-icon-trash"  value="#{bundle.Delete}" actionListener="#{documentosController.destroy}" update=":growl,datalist" disabled="#{empty documentosController.selected}"/>
                        </f:facet>
                    </p:dataTable>
                </p:panel>
            </h:form>

            <ui:include src="Create.xhtml"/>
            <ui:include src="Edit.xhtml"/>
            <ui:include src="View.xhtml"/>
        </ui:define>
    </ui:composition>

</html>

Registro/crudUpdate/web/documentos/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="DocumentosViewDlg" widgetVar="DocumentosViewDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.ViewDocumentosTitle}">
            <h:form id="DocumentosViewForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{documentosController.selected != null}">
                        <h:outputText value="#{bundle.ViewDocumentosLabel_idDocumento}"/>
                        <h:outputText value="#{documentosController.selected.idDocumento}" title="#{bundle.ViewDocumentosTitle_idDocumento}"/>
                        <h:outputText value="#{bundle.ViewDocumentosLabel_nombre}"/>
                        <h:outputText value="#{documentosController.selected.nombre}" title="#{bundle.ViewDocumentosTitle_nombre}"/>
                        <h:outputText value="#{bundle.ViewDocumentosLabel_documento}"/>
                        <h:outputText value="#{documentosController.selected.documento}" title="#{bundle.ViewDocumentosTitle_documento}"/>
                        <h:outputText value="#{bundle.ViewDocumentosLabel_fechaCreacion}"/>
                        <h:outputText value="#{documentosController.selected.fechaCreacion}" title="#{bundle.ViewDocumentosTitle_fechaCreacion}">
                            <f:convertDateTime pattern="MM/dd/yyyy HH:mm:ss" />
                        </h:outputText>
                        <h:outputText value="#{bundle.ViewDocumentosLabel_status}"/>
                        <h:outputText value="#{documentosController.selected.status}" title="#{bundle.ViewDocumentosTitle_status}"/>
                        <h:outputText value="#{bundle.ViewDocumentosLabel_fechaAutorizacion}"/>
                        <h:outputText value="#{documentosController.selected.fechaAutorizacion}" title="#{bundle.ViewDocumentosTitle_fechaAutorizacion}">
                            <f:convertDateTime pattern="MM/dd/yyyy HH:mm:ss" />
                        </h:outputText>
                        <h:outputText value="#{bundle.ViewDocumentosLabel_idUsuario}"/>
                        <h:outputText value="#{documentosController.selected.idUsuario}" title="#{bundle.ViewDocumentosTitle_idUsuario}"/>
                        <h:outputText value="#{bundle.ViewDocumentosLabel_idRev2}"/>
                        <h:outputText value="#{documentosController.selected.idRev2}" title="#{bundle.ViewDocumentosTitle_idRev2}"/>
                        <h:outputText value="#{bundle.ViewDocumentosLabel_idRev1}"/>
                        <h:outputText value="#{documentosController.selected.idRev1}" title="#{bundle.ViewDocumentosTitle_idRev1}"/>
                        <h:outputText value="#{bundle.ViewDocumentosLabel_idAutorizador}"/>
                        <h:outputText value="#{documentosController.selected.idAutorizador}" title="#{bundle.ViewDocumentosTitle_idAutorizador}"/>
                    </p:panelGrid>
                    <p:commandButton value="#{bundle.Close}" onclick="DocumentosViewDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>